//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalNL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierAdmission
    {
        public int IdAdmission { get; set; }
        public string ChirurgieProg { get; set; }
        public Nullable<System.DateTime> DateAdmission { get; set; }
        public Nullable<System.DateTime> DateChirurgie { get; set; }
        public Nullable<System.DateTime> DateConge { get; set; }
        public Nullable<int> NSS { get; set; }
        public Nullable<int> NumeroLit { get; set; }
        public Nullable<int> IdMedecin { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
