//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalNL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBHospitalEntities : DbContext
    {
        public DBHospitalEntities()
            : base("name=DBHospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompagnieAssurance> CompagnieAssurance { get; set; }
        public virtual DbSet<Departement> Departement { get; set; }
        public virtual DbSet<DossierAdmission> DossierAdmission { get; set; }
        public virtual DbSet<Lit> Lit { get; set; }
        public virtual DbSet<Medecin> Medecin { get; set; }
        public virtual DbSet<Parent> Parent { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeLit> TypeLit { get; set; }
        public virtual DbSet<Location> Location { get; set; }
    }
}
